security:
    access_denied_url: home_hello

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            logout: true
            anonymous: true
            form_login:
                login_path: home_hello
            guard:
                authenticators:
                    - App\Security\Authenticator\FacebookAuthenticator

    access_control:
        - { path: ^/settings/, role: ROLE_ADMIN }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/hello, role: IS_AUTHENTICATED_ANONYMOUSLY }

